### ISSUE TITLE
How to get the error text from popup of EditText box in android native application.

### ISSUE THREAD

**Issue by Suneetha-thentu** [xiaocong/uiautomator#104]
Can you please tell me how to get the text from popup while i am clicking on a submit button without  filling the required fields in native android application? That popup is not identifying by the UIAUTOMATORVIEWER. The popup like be in the below image.

http://www.donnfelker.com/wp-content/uploads/2011/11/qonqr-example.png.

Need urgent help.

**Comment by xiaocong** [comment]
Sorry. I don't think uiautomator can help you on the case. An alternative method is to use opencv to find an expected image on the screenshot.

**Comment by SivaKranthiKumar** [comment]
You can try OCR reader like tesseract
