### ISSUE TITLE
the new server does not go easily with uiautomation python wrapper

### ISSUE THREAD

**Issue by mingyuan-xia** [xiaocong/uiautomator#106]
I understand and agree that we should move from old `uiautomator.jar` to the new on in the support lib. But there are a few problems ahead before the [new server](https://github.com/xiaocong/uiautomator) can be fully usable with uiautomation python wrapper:
- [x] now `gradle cC` starts the server but the terminal waits for a `ctrl+c`. Previously the jar server runs silently on the device unless killed via `adb shell kill`
- [x] integration: previously the server builds and sits inside `libs`, the wrapper would automatically install if the server is not found running on the device. Now the wrapper is not aware of how to start/stop the new server
- [ ] build automation, common task automation, etc
I've made some attempts on the third one, see [my fork](https://github.com/mingyuan-xia/uiautomator/blob/master/Makefile) for details.
`all` build the new server; `cleandevice` kicks off the old jar files and kills the old server instance on the device; `run` launches the new server on the device

**Comment by xiaocong** [comment]
Hi @mingyuan-xia 

please check my code on https://github.com/xiaocong/uiautomator/tree/develop/uiautomator. I hope there is no changes for any one to run py-uiautomator, except some new functionalities brought by google android support lib.

Anyway, many thanks for your kindly comments.
