### ISSUE TITLE
how to run script when multiple android devices are connected

### ISSUE THREAD

**Issue by kannukhiladi** [xiaocong/uiautomator#109]
I am trying to run my python script when multiple android devices are connected. I am getting error " raise EnvironmentError("Multiple devices attached but default android serial not set.")
EnvironmentError: Multiple devices attached but default android serial not set." 
This scenarios is taken into __init__.py file under uiautomator folder.

def device_serial(self):
        if not self.default_serial:
            devices = self.devices()
            if devices:
			    #print devices
                if len(devices) is 1:
                    self.default_serial = list(devices.keys())[0]
                else:
                    raise EnvironmentError("Multiple devices attached but default android serial not set.")
            else:
                raise EnvironmentError("Device not attached.")
        return self.default_serial

Below is the result after adb devices
List of devices attached
IPADDRESS1:5555     device
IPADDRESS2:5555     device

However, when running through one device connected, I am able to execute the script. 
 
Please help

**Comment by xiaocong** [comment]
pls try below code:

```python
from uiautomator import Device

d1 = Device("IPADDRESS1:5555")
d2 = Device("IPADDRESS2:5555")
```

or you can take the device serial no from command line,
or get them during runtime by yourself.
