### ISSUE TITLE
Handler not working

### ISSUE THREAD

**Issue by chunnu1** [xiaocong/uiautomator#110]
Scenario: 
1. Type in the message (SMS app). 
2. press back 
3. Dialog opens " discard message"

For this i am creating handler so that whenever this scenario comes it should press OK (to discard message) but handler is not being called. please check the script  below

```
from uiautomator import Device
d=Device("2a2246c")

def fc_close(device):
	print "Handler called..."
	if d(resourceId="android:id/message").exists:
		d(text="OK").click()
	return True

# turn on the handler callback function
d.handlers.on(fc_close)
d.press.back()
d.press.back()
d.press.back()



# turn off the handler callback function
d.handlers.off(fc_close)
```

**Comment by SivaKranthiKumar** [comment]
I think press back will not use handler as it simulates H/W back key. If I am not wrong Handler will be called only when UI object not found.
You can directly call fc_close before calling press.back

**Comment by xiaocong** [comment]
@SivaKranthiKumar is right.

Handler is triggered in case of UiObjectNotFoundException, that means an UI selection fails.

**Comment by chunnu1** [comment]
Thanks all for the clarification.
