### ISSUE TITLE
"clear_text()" works in wrong way

### ISSUE THREAD

**Issue by yangxiaofu0301** [xiaocong/uiautomator#112]
can't clear text!

**Comment by ericvalente** [comment]
I also have this issue.  It appears to try to delete a character, one by one.  It's pretty buggy.  I'd rather it just highlight the whole string and remove it.

**Comment by xiaocong** [comment]
Thank all! It's a known issue. I am looking for a good solution.

**Comment by SivaKranthiKumar** [comment]
```python
d.press(0x0000001d, 0x00001000) # Ctrl+A
d.press("del") # del
````

Temporarily you can use above code

**Comment by ericvalente** [comment]
@SivaKranthiKumar Thank you will try this!!

**Comment by xiaocong** [comment]
:+1: @SivaKranthiKumar
