### ISSUE TITLE
Time Out between two commands

### ISSUE THREAD

**Issue by chunnu1** [xiaocong/uiautomator#113]
Hello All,

I want a time out after each command as my device is slow. I have written almost 200 scripts, so, it will be very tedious task for me to add sleep after each instruction. Is there any option in UIAUTOMATOR to add a delay between each instruction?

**Comment by xiaocong** [comment]
No, current there is no option to add a delay time.

**Comment by SivaKranthiKumar** [comment]
You can inherit UIautomator methods to add timeout (No need change anything in existing code) or use one more wrapper which will in turn call actual UIAutomator APIs (Need to change existing code)
