### ISSUE TITLE
Unable to get the resource-id when running uiautomator events in an adb shell

### ISSUE THREAD

**Issue by Ankit9568** [xiaocong/uiautomator#116]
Hello Team,
we running uiautomator events in an adb shell, should dump all the Accessibility Events but not given the resource-id. return output of click event perform on button 

08-03 12:22:13.520 EventType: TYPE_VIEW_CLICKED; EventTime: 185419; PackageName: com.nimbuzz; MovementGranularity: 0; Action: 0 [ ClassName: android.widget.Button; Text: [IÂ´m new to Nimbuzz]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; IsEnabled: true; IsPassword: false; IsChecked: false; IsFullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0RemovedCount: -1; ParcelableData: null ]; recordCount: 0

I need a resource-id property. Resource used: Android version 4.4

Any help will be highly appricated.

**Comment by xiaocong** [comment]
The latest test support library supports resource-id, but likely uiautomator tool does not yet support it.
