### ISSUE TITLE
How to get and read the text from uiautomator

### ISSUE THREAD

**Issue by kannukhiladi** [xiaocong/uiautomator#118]
Hi,

I am able to click on the applications where the text is matched like d(test="Settings").click().

However, how can I read the text value from uiautomator and save it.

Also, how to differentiate and click two different relative layout in a same page.
Ex. In android Sound and settings how to a select and drag Alram volume and Notification volume.

**Comment by xiaocong** [comment]
`d(text="Settings").info['text']` or `d(text="Settings").text`, it can get the object text.
For operating different relative layout, you can add `instance` parameter in selector.

**Comment by sreekanthsirivella** [comment]
How can i read text using description contains instance
