### ISSUE TITLE
d.dump() returning Unicode strings instead the actual string with special characters

### ISSUE THREAD

**Issue by shankarkumaryelapu** [xiaocong/uiautomator#125]
d.dump() returning Unicode strings instead the actual string with special characters

For example : I want to use 

d(text="Wi-1Fi").right(className="android.widget.Switch").click()

but this will raise an uiObject not found exception

to avoid this we need to use it as d(text=u"Wi\u2011Fi").right(className="android.widget.Switch").click()

Please made it more generic as you mentioned in your document

**Comment by xiaocong** [comment]
@shankarkumaryelapu they are different characters.
```python
>>> ord('-')
45
>>> ord('\u2011')
8209
>>> print('-')
-
>>> print('\u2011')
‑
```
