### ISSUE TITLE
在多台设备中运行watcher貌似只能在一台设备起作用

### ISSUE THREAD

**Issue by kevinkelin** [xiaocong/uiautomator#127]
我尝试在同时在多台设备中运行脚本，每个设备在不同的线程中跑，都初始了各自的d=Device(Serial),也在各自的线程中初始化watcher，只是我将d.watchers.run()又放在单独的线程中跑，也就是说，如果有二台设备，那么会有四个线程在跑，二个线程跑测试脚本，二个线程跑watcher，但是现在的问题是只有一台设备能够影响watcher中的事件，另外一台不能响应，如果只跑一台设备watcher是好用的

**Comment by kevinkelin** [comment]
问题搞定了，在初始化d的时候为每个手机选用不同的local_port端口即可

**Comment by xiaocong** [comment]
:+1:
