### ISSUE TITLE
handler该如何使用？

### ISSUE THREAD

**Issue by kevinkelin** [xiaocong/uiautomator#128]
我想使用handler的功能来实现当某一个UI selector  出现以后对其进行点击，我按照readme里的说明写，可以怎么也不能实现

    def checkcancel(d):
        print 'entering handler...'
        if d(text=u'取消').exists:
           d(text=u'取消').click()
        else:
            print 'not found...'

        
    if __name__ == '__main__':
        print d.info
        d.handlers.on(checkcancel)    
        time.sleep(30)
实际的运行中，既没有打印出entering handler...也没有打印出not found,在界面上有取消按钮的时候也没有对其进行点击，感觉好像根本就没有进行调用这个checkcancel函数，是我的写法有什么问题吗？

**Comment by xiaocong** [comment]
handler是watcher的一个替代机制, 优点是能直接用python写处理方法, 缺点是运行速度偏慢. 使用的场景是, 当有UiObjectNotFound的异常抛出的时候, 可以在handler函数中处理, 然后继续执行case, 而不是抛出error. 

例如, 当在执行case的时候, 如果有个陌生人给被测手机打个电话, 会造成你的case出error. 但如果你写个incoming call的handler, 就可以在出现异常的地方挂掉电话, 然后继续执行case.
