### ISSUE TITLE
dump api failing due to Illegal character !

### ISSUE THREAD

**Issue by xh84** [xiaocong/uiautomator#129]
when i use dump api, i get the error:

>>> d.dump("aaaa.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\lib\site-packages\uiautomator\__init__.py", line 602, in dump
    content = self.server.jsonrpc.dumpWindowHierarchy(compressed, None)
  File "D:\Python27\lib\site-packages\uiautomator\__init__.py", line 432, in wrapper
    return _method_obj(*args, **kwargs)
  File "D:\Python27\lib\site-packages\uiautomator\__init__.py", line 131, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: 0, Message: java.lang.IllegalArgumentException: Illegal character (d83c)

**Comment by xiaocong** [comment]
@xh84 please help upload logcat on device. Thx

**Comment by kingname** [comment]
I have met the same Exception.

**Comment by pedia** [comment]
I have same issue, logcat below:

> W/JsonRpcServer(27614): Error in JSON-RPC Service
> W/JsonRpcServer(27614): java.lang.reflect.InvocationTargetException
> W/JsonRpcServer(27614): 	at java.lang.reflect.Method.invokeNative(Native Method)
> W/JsonRpcServer(27614): 	at java.lang.reflect.Method.invoke(Method.java:515)
> 
> ...
> 
> W/JsonRpcServer(27614): 	at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpNodeRec(AccessibilityNodeInfoDumper.java:84)
> W/JsonRpcServer(27614): 	at android.support.test.uiautomator.AccessibilityNodeInfoDumper.dumpWindowHierarchy(AccessibilityNodeInfoDumper.java:49)
> W/JsonRpcServer(27614): 	at android.support.test.uiautomator.UiDevice.dumpWindowHierarchy(UiDevice.java:946)
> W/JsonRpcServer(27614): 	at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:178)
> W/JsonRpcServer(27614): 	at com.github.uiautomator.stub.AutomatorServiceImpl.dumpWindowHierarchy(AutomatorServiceImpl.java:164)
> W/JsonRpcServer(27614): 	... 11 more
