### ISSUE TITLE
How to click on the button which doesn't have text

### ISSUE THREAD

**Issue by kannukhiladi** [xiaocong/uiautomator#131]
Hi,

I have an application which have a button (three dots) usually more options in android. How can I click on that using uiautomator in python.

Regards,
Karan
![more_option](https://cloud.githubusercontent.com/assets/13198649/9957146/71d11d3a-5e1b-11e5-9faf-8761a0142186.jpg)

**Comment by xiaocong** [comment]
`d(className="android.widget.ImageButton", description="More options")`
