### ISSUE TITLE
how to improve the execution speed of click

### ISSUE THREAD

**Issue by niuniudd** [xiaocong/uiautomator#132]
while True:
    device.watcher("test").when(text=u'蓝牙').click(text=u'蓝牙')
    t1 = time.time()
    device.watchers.run()
    #os.system('adb shell input tap 223 640')
    t2 = time.time()
    print "time:%s"%str(t2-t1)
    device.press.back()
result:
time:1.89100003242
time:1.90000009537
time:1.85199999809
time:1.88599991798
time:1.82999992371
time:1.867000103
time:1.88199996948
time:1.86899995804
time:1.8710000515
time:1.94200015068
time:2.38999986649
time:1.91300010681
I Found the speed is slow
when i use os.system('adb shell input tap 223 640')，the cost time is only about 0.6

Can you improve method:watcher get the Position(x,y) at first time ,and always click this position?

**Comment by xiaocong** [comment]
Watcher is a mechanism of Android UiAutomator service.

A watcher is trigger in case of an ui selection failure. Most time is spent on ui selection failure(timeout), and only ~100ms on performing click action. So I have no way to improve it.

Anyway, thanks for your suggestion.
