### ISSUE TITLE
video freezing

### ISSUE THREAD

**Issue by venkatmaka** [xiaocong/uiautomator#147]
Hi,
I would like to know how to handle the video freeze scenario using uiautomator.

use case:
while video is streaming suddenly it goes to black screen and there is no further action.

please let me know how to handle this scenario in uiautomator.

Thanks in advance.
Rgrds,
venkat.

**Comment by SivaKranthiKumar** [comment]
May I know, how u fixed it?

**Comment by venkatmaka** [comment]
Hi Kranthikumar,

I have noticed  Fps value is going to value zero when video is freezes
So we can monitor the Fps values and conclude the issue.

Rgrds,
Venkat.

**Comment by SivaKranthiKumar** [comment]
thanks
