### ISSUE TITLE
d.dump() missing views then stuck in bad state

### ISSUE THREAD

**Issue by kevin-brotcke** [xiaocong/uiautomator#156]
I keep hitting a bug where resource IDs suddenly disappear, even though the device state hasn't changed and can verify in uiautomatorviewer. I'm able to reproduce the bug in as few lines as:

```
# At home screen of device tested
>>> from uiautomator import device as d
>>> d.server.stop()  # Make sure we are in a good state
>>> d(resourceId='android:id/navigationBarBackground).exists
True
>>> d.dump()  # Does not show the full view hierarchy, navigationBarBackground missing
>>> d(resourceId='android:id/navigationBarBackground').exists
False
```

At this point it will continue to return False until I restart the uiautomator server or kill the adb service.

To find a specific example, take a uiautomator dump with uiautomatorviewer first, then take one using the Python wrapper. Nodes that appear near the bottom of uiautomatorviewer do not always show up in d.dump().

### Environment info
uiautomator: 0.2.6
device: [Amazon Fire HD 6](http://smile.amazon.com/gp/product/B00KC6I06S)
OS: Ubuntu 14.04 LTS

**Comment by kevin-brotcke** [comment]
Note this isn't reproducible by using `d.dump(compressed=False)`. I think what's happening is that `AutomatorServiceImpl.dumpWindowHierarchy` is setting `device.setCompressedLayoutHeirarchy(compressed)`, but never changes it back to uncompressed. Once `d.dump(compressed=True)` is called, all calls after reuse `device` and return a compressed view hierarchy resulting in missing resource IDs.

**Comment by hongbinbao** [comment]
hi,
have a try follow your description. Once the compressed mode was set. The nodes which was regarded as "FLAG_INCLUDE_NOT_IMPORTANT_VIEWS" will be removed by accessibility framework.

**Comment by kevin-brotcke** [comment]
Fix merged.

**Comment by greenheart0707** [comment]
The info is null when I use d.dump() to dump device's info, while it was normal if I dump device's info in serial(By launch the command "uiautomator dump xx.xml"), what's more, device's UI info can also be obtained by adb shell(Enther into adb shell, and launch the command of "uiautomator dump xx.xml"), I don't know why.

[xml_file.zip](https://github.com/xiaocong/uiautomator/files/977926/xml_file.zip)

**Comment by shfscut** [comment]
@greenheart0707 
hi  i have encountered the same question,  have you solved this problem??

**Comment by SivaKranthiKumar** [comment]
I am also facing same issue :(
