### ISSUE TITLE
Information about apks/jars in uiautomator/uiautomator/libs/

### ISSUE THREAD

**Issue by agrprashant** [xiaocong/uiautomator#158]
Hi, 

I am trying to understand where the files in uiautomator/uiautomator/libs/ are coming from and how to re-build them. 

My current understanding is that they are coming from just one project: https://github.com/xiaocong/android-uiautomator-server

Is that correct (if yes, then please share the instructions)? If not, could you please help point me in the right direction?

Thanks in advance.
Prashant

**Comment by xiaocong** [comment]
@agrprashant Yes, you r right.
[android-uiautomator-server](https://github.com/xiaocong/android-uiautomator-server) can build two apks, which are needed to run jsonrpc server. Other two jars under `libs` directory are only for android lower than 4.4.

**Comment by agrprashant** [comment]
Okay, thanks very much for confirming it. 
Just to be sure:
1. app-uiautomator.apk points to the main apk in android-uiautomator-server
2. app-uiautomator-test.apk points to the test apk in android-uiautomator-server

I guess the jars are also coming from that project but were built manually (do you have any instructions for that)?

**Comment by xiaocong** [comment]
jar files are built from https://github.com/xiaocong/android-uiautomator-jsonrpcserver.

**Comment by agrprashant** [comment]
Awesome. Thanks for confirming. I've been trying to figure this out for few days now.
Do you think I can add these instructions somewhere? (like to readme file)?

**Comment by xiaocong** [comment]
Yes, you are welcome.
