### ISSUE TITLE
IOError: RPC server not started!

### ISSUE THREAD

**Issue by ZhouLihua** [xiaocong/uiautomator#16]
Hi:
 I had problems to start the RPC server.

> > > from uiautomator import device as d
> > > 
> > > d.info
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/uiautomator.py", line 412, in info
> > >     return self.server.jsonrpc.deviceInfo()
> > >   File "/usr/local/lib/python2.7/dist-packages/uiautomator.py", line 319, in jsonrpc
> > >     self.start()
> > >   File "/usr/local/lib/python2.7/dist-packages/uiautomator.py", line 337, in start
> > >     raise IOError("RPC server not started!")
> > > IOError: RPC server not started!

Did i forgot some steps?

**Comment by cnritng** [comment]
it seems like it's the storage problem which cause this.
