### ISSUE TITLE
必须有Android SDK吗？

### ISSUE THREAD

**Issue by ATcn** [xiaocong/uiautomator#164]
试了下，把JDK干掉，那么SDK也该失效了，UIautomator还是能跑通。

看了logcat，UI自动化的关键是能够向手机/data/写入jar文件，这样PC端脚本就可以控制手机了。

作为python新人，很想知道SDK或ADB工具对于python版的UIauyomator是必须的吗？它们的作用是什么？

**Comment by hongbinbao** [comment]
adb是必须的，adb forward是关键
SDK不是必须的，如果是ubuntu你可以直接apt-get install 来安装adb, 确保adb可执行文件在系统命令的search path里可以找到。

**Comment by ATcn** [comment]
3Q 明白了
