### ISSUE TITLE
python multiprocessing and multiple devices is terribly slow

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [xiaocong/uiautomator#180]
- Scan for adb devices
- for each spin up a uiautomator using multiprocess.Pool.apply_aync

  p=Pool(processes=len(devices))
  for device in devices:
    p.apply_async(worker,(device,))
  p.close()
  p.join()

-----
But when i do a scroll of list in all the processes, only one device scrolls at a time. I cant get the sub-processes uiautomators work independently. They seem to block on/wait for each other. And only one working at a time.

Should i use any different way of spinning up the processes or is there any uiautomator setting i should be looking at.

**Comment by SivaKranthiKumar** [comment]
We successfully ran on more than 20 devices simultaneously. We used subprocess.Popen to run same script on multiple devices.

**Comment by jagan-veeraraghavan** [comment]
@SivaKranthiKumar thanks for that reply, I rewrite the python script from multiprocessing to subprocess.Popen . But when each Each subprocess is still blocking. I run them on Raspberry PI. I will try to run it on my Mac and see if it is in any way a limitation of Raspberry PI or the custom build of  adb for ARM.

**Comment by reddypdl** [comment]
@jagan-veeraraghavan , use pytset framework with xdist plugin , more info on how to get the same script run on multple deices is @ https://holgerkrekel.net/2013/11/12/running-tests-against-multiple-devicesresources-in-parallel/
