### ISSUE TITLE
How to implement regular expression object matching

### ISSUE THREAD

**Issue by shfscut** [xiaocong/uiautomator#221]
device(textMatches=re.complie('Settings', re.I)
to implement case insensitive, i need to use regular expression objects. But the corresponding selector is Uiselector instead of BySelector. i know Byselector support text (Pattern textValue), how should I use？

**Comment by SivaKranthiKumar** [comment]
you can use d(textMatches="(?i)Settings"). AFAIK we have to use java regexp here

**Comment by shfscut** [comment]
@SivaKranthiKumar Thank you very much!
this is a very good way. very effective
