### ISSUE TITLE
Can we do getParent()

### ISSUE THREAD

**Issue by Moriarty16** [xiaocong/uiautomator#225]
Hi , I uses to do the UI test with java , now I wish to learn some python.
I'm wondering if there is a method like 'getParent()' to get a parent object .
Really looking forward to your reply , thanks .

**Comment by SivaKranthiKumar** [comment]
unfortunately it's not available :(

**Comment by tuanchauict** [comment]
In UIAutomator, UIObject2 has getParent() method

https://developer.android.com/reference/android/support/test/uiautomator/UiObject2.html

**Comment by codeskyblue** [comment]
@tuanchauict seems a good idea
