### ISSUE TITLE
Once start jsonrpc, user encounter "android.accessibilityservice.IAccessibilityServiceClient has already registered" issue

### ISSUE THREAD

**Issue by hongnaxu** [xiaocong/uiautomator#25]
hi, dear xiaocong
     when running execution through jsonrpc, user is unable to use ui-automator viewer to design next case step or run adb shell uiautomator runtest from terminal, shall we support another kind of mode --- case design mode, it will permit user to use ui-automator command.
Error logs:

---

INSTRUMENTATION_RESULT: shortMsg=java.lang.IllegalStateException
INSTRUMENTATION_RESULT: longMsg=UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@6a64d4a8already registered!
INSTRUMENTATION_CODE: 0

---

**Comment by pritamrathi92** [comment]
HI xiaocong, Is there any way ti run uiautomator from shell also once used in python?
In my case, in python script, I am using uiautomator module and .jar (since already written for a particular case, dont want to write it again) as well

**Comment by xiaocong** [comment]
@pritamrathi92 sorry, I don't know.
