### ISSUE TITLE
How to determine I have swiped to the end?

### ISSUE THREAD

**Issue by volity** [xiaocong/uiautomator#272]
Hi, I use swipe() to turn page down. How to determine I have swiped to the bottom of the page?

**Comment by volity** [comment]
Does uiautomator have relative functions?  If not, should I compare the picture current step with last step?

**Comment by SivaKranthiKumar** [comment]
Swipe function usually returns false if it is end of the scroll. But it is not working properly
You can compare the XML dumps to check the scroll end reliably

**Comment by volity** [comment]
Thanks a lot. Normally, the most simple way is comparing the XML String. However when the page has the object which NAF=true, such as banner with carousel images, XML String compare can not work. So can you give me some advices for XML comparing?  Thank you again for your reply.

**Comment by volity** [comment]
The examples of banner with carousel images like this:
`<node index="0" resource-id="" text="" class="android.view.View" package="com.fenbi.android.zenglish" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[45,72][1035,125]"/>
<node NAF="true" index="1" resource-id="" text="" class="android.widget.ImageView" package="com.fenbi.android.zenglish" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[45,72][1035,125]"/>`

`<node NAF="true" index="0" resource-id="" text="" class="android.widget.ImageView" package="com.fenbi.android.zenglish" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[45,291][1035,694]"/>
<node index="1" resource-id="" text="" class="android.view.View" package="com.fenbi.android.zenglish" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[45,291][1035,694]"/>`

**Comment by SivaKranthiKumar** [comment]
You can compare full XML dump. Before scroll take the dump, after scroll again take the dump. Now compare both
