### ISSUE TITLE
I use d(clickable='true') get all clickable objects, then how to filter object by resourceId? 

### ISSUE THREAD

**Issue by volity** [xiaocong/uiautomator#273]
After I got all clickable objects, I want to click these objects except for return key in the upper left conner. So how to filter the return key ?

**Comment by SivaKranthiKumar** [comment]
You can loop through all the objects & get the resourceID using obj.info

**Comment by volity** [comment]
The obj.info does not have resourceId attribute. When printing obj.info, the result like this:
`{u'contentDescription': u'', u'checked': True, u'clickable': False, u'scrollable': False, u'text': u'\u8bfe\u7a0b', u'packageName': u'com.fenbi.android.zenglish', u'selected': False, u'enabled': True, u'bounds': {u'top': 1903, u'left': 102, u'right': 168, u'bottom': 2023}, u'className': u'android.widget.CheckedTextView', u'focusable': False, u'focused': False, u'checkable': True, u'resourceName': None, u'longClickable': False, u'visibleBounds': {u'top': 1903, u'left': 102, u'right': 168, u'bottom': 2023}, u'childCount': 0}
`
So I get the first obj of all clickable objects and use visibleBounds to determine if the obj is return key, the premise is that the size of the return key is within a certain range. Thank you anyway.

**Comment by volity** [comment]
Sorry, I mistakenly thought that there is no resourceId in obj.info. The resourceId will be available when the object has a resourceId.

**Comment by volity** [comment]
Or use dump, there is resource-id in the xml file. [https://github.com/xiaocong/uiautomator/issues/92](url)
