### ISSUE TITLE
How to Get location coordiate (x,y)

### ISSUE THREAD

**Issue by monicadanesa** [xiaocong/uiautomator#278]
Hi anyone, May I Know How get location element (return x,y)?
as I know if i use device.info it will return bound and invisible bound.

**Comment by ionestel** [comment]
@monicadanesa, I don't think this uiautomator package has a way to do that, but perhaps you can compute the desired position based on the target UI element's bounds (see below).

```python
def get_center(self, resource_id):
    ui_element = self.dev(resourceId=resource_id)
    if ui_element.exists:
        bounds = ui_element.info.get("visibleBounds") or ui_element.info.get("bounds")
        x = (bounds["left"] + bounds["right"]) / 2
        y = (bounds["top"] + bounds["bottom"]) / 2
        return (x, y)
    return False
```

The example code gets the center position of the UI element based on its resource ID, but you can change it however way that fits your needs.

**Comment by monicadanesa** [comment]
hey, @ionestel  thanks for the reply.
thank you for the solution it really clear

Cheers,

Monica
