### ISSUE TITLE
Initialization error in 1.0.1: TypeError: '>=' not supported between instances of 'method' and 'int'

### ISSUE THREAD

**Issue by jonbeeler** [xiaocong/uiautomator#295]
uiautomator 1.0.1 intialization is failing on line 475 because the sdk_version method is being checked instead of the value.

[...]lib/python3.6/site-packages/uiautomator/__init__.py", line 475, in start
    elif self.sdk_version >= 28:
TypeError: '>=' not supported between instances of 'method' and 'int'

See line 468:
        if self.sdk_version() < 18:
Line 475:
        elif self.sdk_version >= 28:

**Comment by jonbeeler** [comment]
I created a pull request with the fix: https://github.com/xiaocong/uiautomator/pull/296

**Comment by hongbinbao** [comment]
pip install uiautomator==1.0.2
python3 -m pip install uiautomator==1.0.2
