### ISSUE TITLE
sometimes, click() returned False.

### ISSUE THREAD

**Issue by Andromeda606** [xiaocong/uiautomator#315]
I don't know why, but sometimes the click operation returns false in the code I wrote. I don't know what am I doing wrong.

```PYTHON
from uiautomator import device as d


print(d.click(500,500))
```

please help me.. 
This code sometimes works, sometimes it doesn't. I tried typing adb kill-server but it didn't work.

**Comment by unofficialdxnny** [comment]
hello, clicking on specific coordinates also did not work for me. it is also not a good practice. you should instead find resource ids of elements on the screen and click those instead.

You can find these in the UI Hierarchy, Simply have your device connected and open up on the page/screen where the element is located

# 1. Dump Hierarchy Script
This script will dump the current screen hierarchy and save it to the device's storage as an XML file.
(Windows)
Script: `dump_hierarchy.bat`

```bat
@echo off
REM Dump the current screen hierarchy to an XML file on the device

REM Set the file name for the dumped hierarchy
set filename=/sdcard/hierarchy.xml

REM Dump the UI hierarchy
adb shell uiautomator dump %filename%

REM Inform the user that the dump was successful
echo UI hierarchy dumped to %filename%
```
# 2. Pull Hierarchy Script
This script will pull the previously dumped screen hierarchy XML file from the device to your computer.

Script: `pull_hierarchy.bat`

```bat
@echo off
REM Pull the screen hierarchy XML file from the device to the current directory

REM Set the file name and destination
set filename=/sdcard/hierarchy.xml
set destination=hierarchy.xml

REM Pull the hierarchy XML file from the device
adb pull %filename% %destination%

REM Inform the user that the file was pulled successfully
echo UI hierarchy pulled to %cd%\%destination%
```

Find the `resourceid` in this file (saves where the terminal is open) `ctrl` + `f` and search a name for it. you want to locate the one that says `clickable=true`

copy the `resource id` and than in your script you can just do

```py
import uiautomator2 as u2

# Connect to the device (USB or IP)
device = u2.connect()  # This will connect to the first available device

# Example: Specify a resource ID
resource_id = "com.example.app:id/button_id"

# Click on the element with the specified resource ID
device(resourceId=resource_id).click()

# Optional: Add a message to confirm the click action
print(f"Clicked on element with resource ID: {resource_id}")
```

**Comment by Andromeda606** [comment]
This solved my problem. Thanks!
