### ISSUE TITLE
set_text failed due to different Input Method Keyboard

### ISSUE THREAD

**Issue by jjqq2013** [xiaocong/uiautomator#75]
set_text often failed due to the key event is sent to Input Method Keyboard, so they are converted to other char.
Someone made a special keyboard for UIAutomation: https://github.com/sumio/uiautomator-unicode-input-helper, but can not use it directly in this project, it will be great helpful if you add this to python.

**Comment by jjqq2013** [comment]
https://github.com/sumio/uiautomator-unicode-input-helper

Sorry it seems I happened to deleted my repo so the precompiled jar file get lost. You might need comiple it from source.

**Comment by 1800959** [comment]
Thanks for your reply! I'm new to java, I used eclipse to compile utf7ime to an apk. Is Utf7ImeHelper.jar compile from Utf7ImeHelper.java?

**Comment by jjqq2013** [comment]
I am not sure. Seems need compile a jar and a apk, 

The jar is from https://github.com/sumio/uiautomator-unicode-input-helper/tree/master/UiAutomatorInputSample

**Comment by 1800959** [comment]
You mean I need to compile the whole UiAutomatorInputSample folder to a jar?
