### ISSUE TITLE
Installation fail on win7

### ISSUE THREAD

**Issue by rishikamaljha** [xiaocong/uiautomator#83]
Hello,

I am very new to android testing. I am installing this tool. I followed below steps.

1. Downloaded Android SDK and set the path. adb commands works correctly.
2. Downloaded python 3.4
3. From CMD i ran command "pip install uiautomator" -> here i get failure "NameError: name 'urllib3' is not defined"
 Can you please help me in this.

Thanks,
Rishi

**Comment by xiaocong** [comment]
track it  with #102
