### ISSUE TITLE
User can set temporary directory to avoid ( httplib.BadStatusLine: '') error

### ISSUE THREAD

**Issue by vsantari** [xiaocong/uiautomator#90]
Is there a way can user set it's own temporary directory instead of sdcard folder to avoid  httplib.BadStatusLine: '') error.?

**Comment by xiaocong** [comment]
Please tell me if you find a way. My answer is no.

**Comment by vsantari** [comment]
May I know what's the reason behind?

**Comment by xiaocong** [comment]
I am using NanoHttpd as http backend of jsonrpc server. You can check its code [here](https://github.com/NanoHttpd/nanohttpd/blob/master/core/src/main/java/fi/iki/elonen/NanoHTTPD.java#L473).
