### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by tiann** [xiaocong/uiautomator#93]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with uiautomator. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable uiautomator on @Sourcegraph by going to https://sourcegraph.com/github.com/xiaocong/uiautomator and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by xiaocong** [comment]
done
