### ISSUE TITLE
d1(textMatches="^([0-9a-fA-F][0-9a-fA-F]:){5}([0-9a-fA-F][0-9a-fA-F])$").info does not match mac address TextView e.g. 40:83:de:7e:49:12 

### ISSUE THREAD

**Issue by reddypdl** [xiaocong/uiautomator#95]
just throws an empty response.

uiautomator version - '0.1.34'
android platform - 4.1.1

{u'bounds': {u'bottom': 752, u'left': 0, u'right': 1280, u'top': 0},
 u'checkable': False,
 u'checked': False,
 u'childCount': 1,
 u'className': None,
 u'clickable': False,
 u'contentDescription': u'',
 u'enabled': True,
 u'focusable': False,
 u'focused': False,
 u'longClickable': False,
 u'packageName': u'com.android.settings',
 u'scrollable': False,
 u'selected': False,
 u'text': u'',
 u'visibleBounds': None}

**Comment by xiaocong** [comment]
Hi, it passed on my side.
```
>>> d(textMatches="^([0-9a-fA-F][0-9a-fA-F]:){5}([0-9a-fA-F][0-9a-fA-F])$").text
u'40:83:de:7e:49:12'
```

Please use uiautomatorviewer to check what's exactly the text in your device.
