### ISSUE TITLE
Help on adb connect to remote adb server and device

### ISSUE THREAD

**Issue by luisxiaomai** [xiaocong/uiautomator#96]
xiaocong 你好，

我想尝试"Speficy the adb server host and port running on other computer"这种连接模式， 但是老是报“device not attached”. @xiaocong 能否帮忙指导下可能没有配置好的地方。

我是这么做的:
##### 远程虚拟机起adb server, 手机是连接在虚拟机上的: 
```
adb -a -P 5037 fork-server server &
```

##### 本机写python 脚本：
```
from uiautomator import Device
d = Device('014E05DE0F02000E', adb_server_host='192.168.1.68', adb_server_port=5037)
d.info
``` 

环境：
最新你的uiautomator python库，
android sdk是4.4

谢谢
luis

**Comment by xiaocong** [comment]
我没在虚拟机上试过，但在实体主机上是没问题的。
建议用几个步骤进行排查：
1. 在运行`adb -a -P 5037 fork-server server`前确保你已经杀死了adb server: `adb kill-server`
2. 用实体主机进行测试，如果同样的步骤能连接实体主机的adb server，说明是虚拟机的原因；
3. 在虚拟机上使用adb，查看是否能列出用usb连接的设备；有些虚拟机需要进行USB设备的映射才能使用物理连接的USB设备。
4. 检查虚拟机的网络是否通畅；
5. 在其他主机上运行`adb -H 192.168.1.68 devices`查看是否能连接上

希望这些步骤能帮你解决这个问题

**Comment by QianJin2013** [comment]
小聪你好
关于adbhost这个提问的人的需求  我都搞好了
https://github.com/sjitech/android-uiautomator

实在不好意思 我试图把他合并到你那里 结果总是出错 又不好意思麻烦你 就提出合并了。 你们要是有兴趣可以看看diff。



2015年3月31日火曜日、贺晓聪<notifications@github.com>さんは書きました:

**Comment by luisxiaomai** [comment]
@Qianjin2013 你fork的是ok。
@xiaocong 多谢回答，建议merge@Qianjin2013 的change,或者做相应修改。

**Comment by QianJin2013** [comment]
哦 顺便说一个有点关联的事儿 我发现名叫Device的global instance定义有点碍事： 如果我只import
uiautomator并不想执行任何针对本地的device查询（因为我想用remote adb host），居然也会导致本地adb查询，于是有两个坏处
一是慢 而是如果本地没有device时会出个错误让人费解。这个毛病解释起来很啰嗦 毕竟是小众用户 于是我索性改掉了
似乎commit了。可是试图合并也失败了 都是在自动测试script上失败的。

2015年3月31日火曜日、luxiaomai<notifications@github.com>さんは書きました:

**Comment by xiaocong** [comment]
多谢 @QianJin2013 以前我将这个问题想简单了，早期的改动有很多问题。我提了PR将你的改动合并进来了，但挪除了部分改动，请帮忙测试下。

**Comment by QianJin2013** [comment]
OK，谢谢。我有空时就去测一下。

2015年4月2日木曜日、贺晓聪<notifications@github.com>さんは書きました:
